import type {
  PlayerTurnPhaseArgs,
} from "./battleTurnPhasePlayerArgTypes";
import { resolvePlayerActionPhase } from "./battleTurnPhasePlayerActionPhase";
import type { PlayerTurnPhaseResult } from "./battleTurnPhasePlayerTypes";

export const resolvePlayerTurnPhase = ({
  currentTimeMs,
  turn,
  player,
  enemy,
  logs,
  passiveFlags,
  pVsE,
  bossBroken,
  playerDebuffed,
  playerHp,
  playerMp,
  enemyHp,
  playerStatuses,
  enemyStatuses,
  activeSkill,
  activeSkillReadyAtMs,
  mageFoundationStacks,
  swordHeartStacks,
  playerAttackIntervalMs,
  nextSwordImmortalGuardAtMs,
  hasMageFusionPassive,
  hasSwordImmortalPassive,
  dependencies,
}: PlayerTurnPhaseArgs): PlayerTurnPhaseResult =>
  resolvePlayerActionPhase({
    currentTimeMs,
    turn,
    player,
    enemy,
    logs,
    passiveFlags,
    pVsE,
    bossBroken,
    playerDebuffed,
    playerHp,
    playerMp,
    enemyHp,
    playerStatuses,
    enemyStatuses,
    activeSkill,
    activeSkillReadyAtMs,
    mageFoundationStacks,
    swordHeartStacks,
    playerAttackIntervalMs,
    nextSwordImmortalGuardAtMs,
    hasMageFusionPassive,
    hasSwordImmortalPassive,
    dependencies,
  });
